import type { Meta, StoryObj } from '@storybook/react';
import { BlogSEO, generateBlogMetadata, generateBlogJSONLD } from '../src/components/BlogSEO';
import { BlogHead } from '../src/components/BlogHead';
import { BlogPreview } from '../src/components/BlogPreview';
import type { BlogPost } from '../src/types';
import type { SEOConfig } from '../src/types/seo';
import { analyzeContent, getSEOScore } from '../src';

// Sample SEO configuration
const seoConfig: SEOConfig = {
  siteUrl: 'https://example.com',
  siteName: 'My Awesome Blog',
  defaultAuthor: {
    name: 'John Doe',
    url: 'https://example.com/author/john-doe',
    image: 'https://example.com/images/john-doe.jpg',
    social: {
      twitter: '@johndoe',
      github: 'https://github.com/johndoe',
    },
  },
  defaultImage: {
    url: 'https://example.com/images/default-og.jpg',
    width: 1200,
    height: 630,
    alt: 'My Awesome Blog',
  },
  twitterSite: '@myawesomeblog',
  defaultLanguage: 'en',
  publisher: {
    name: 'My Awesome Blog',
    url: 'https://example.com',
    logo: {
      url: 'https://example.com/logo.png',
      width: 600,
      height: 60,
    },
  },
  enableStructuredData: true,
  autoGenerateDefaults: true,
};

// Sample blog post with full SEO metadata
const samplePostWithSEO: BlogPost = {
  id: '1',
  title: 'Complete Guide to SEO Optimization in React Applications',
  slug: 'complete-guide-seo-optimization-react',
  excerpt: 'Learn how to implement comprehensive SEO strategies in your React applications, including meta tags, Open Graph, and structured data.',
  featuredImage: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a',
  createdAt: '2024-01-15T10:00:00Z',
  updatedAt: '2024-01-20T15:30:00Z',
  publishedDate: '2024-01-15T10:00:00Z',
  modifiedDate: '2024-01-20T15:30:00Z',
  author: {
    name: 'Sarah Johnson',
    url: 'https://example.com/author/sarah-johnson',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    bio: 'SEO specialist and React developer with 10+ years of experience',
    social: {
      twitter: '@sarahjohnson',
      linkedin: 'https://linkedin.com/in/sarahjohnson',
      github: 'https://github.com/sarahjohnson',
    },
  },
  category: 'Web Development',
  tags: ['SEO', 'React', 'Next.js', 'Web Performance', 'Meta Tags'],
  seo: {
    description: 'Comprehensive guide covering meta tags, Open Graph protocol, Twitter Cards, JSON-LD structured data, and best practices for SEO in React apps.',
    keywords: ['SEO', 'React SEO', 'Next.js SEO', 'Meta tags', 'Open Graph', 'Structured data', 'JSON-LD'],
    robots: 'index, follow',
    language: 'en-US',
  },
  openGraph: {
    title: 'Complete Guide to SEO Optimization in React | My Awesome Blog',
    description: 'Master SEO in React with this comprehensive guide covering all aspects from meta tags to structured data.',
    type: 'article',
    image: {
      url: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a',
      width: 1200,
      height: 630,
      alt: 'SEO optimization concept with charts and analytics',
    },
  },
  twitter: {
    card: 'summary_large_image',
    creator: '@sarahjohnson',
  },
  sections: [
    {
      id: '1',
      type: '1-column',
      columns: [
        [
          {
            id: 'intro',
            type: 'text',
            content: `# Introduction to SEO in React

Search Engine Optimization (SEO) is crucial for any web application. In this comprehensive guide, we'll explore how to implement professional SEO strategies in React applications.

## Why SEO Matters

SEO helps your content reach the right audience by improving visibility in search engines. With proper implementation, you can:

- Increase organic traffic
- Improve user engagement
- Build brand credibility
- Enhance social media sharing

Let's dive into the technical details of implementing SEO in React applications.`,
          },
        ],
      ],
    },
    {
      id: '2',
      type: '2-columns',
      columns: [
        [
          {
            id: 'meta-tags',
            type: 'text',
            content: `## Meta Tags

Meta tags are essential HTML elements that provide metadata about your webpage. The most important meta tags for SEO include:

### Title Tag
The title tag appears in search results and browser tabs. Keep it under 60 characters.

### Meta Description
A brief summary of your page content (150-160 characters recommended).

### Viewport Tag
Essential for mobile responsiveness and mobile SEO.`,
          },
        ],
        [
          {
            id: 'og-tags',
            type: 'text',
            content: `## Open Graph Protocol

Open Graph tags control how your content appears when shared on social media platforms like Facebook, LinkedIn, and Slack.

### Key OG Tags
- og:title
- og:description
- og:image
- og:url
- og:type

These tags ensure your content looks professional when shared.`,
          },
        ],
      ],
    },
    {
      id: '3',
      type: '1-column',
      columns: [
        [
          {
            id: 'quote',
            type: 'quote',
            content: 'SEO is not about gaming the system anymore; it\'s about learning how to play by the rules.',
            author: 'Jordan Teicher',
            role: 'Content Strategist',
          },
        ],
      ],
    },
  ],
};

// Sample post with minimal SEO (auto-generation demo)
const samplePostMinimalSEO: BlogPost = {
  id: '2',
  title: '10 Tips for Better React Performance',
  slug: '10-tips-better-react-performance',
  tags: ['React', 'Performance', 'Optimization'],
  sections: [
    {
      id: '1',
      type: '1-column',
      columns: [
        [
          {
            id: 'intro',
            type: 'text',
            content: `React performance optimization is essential for building fast, responsive applications. Here are 10 practical tips to improve your React app's performance.

## 1. Use React.memo

Memoization prevents unnecessary re-renders of functional components. Wrap components that receive the same props frequently.

## 2. Implement Code Splitting

Use React.lazy() and Suspense to split your code into smaller bundles that load on demand.

## 3. Optimize Images

Use modern image formats like WebP and implement lazy loading for images below the fold.`,
          },
        ],
      ],
    },
  ],
};

const meta: Meta<typeof BlogSEO> = {
  title: 'SEO/BlogSEO',
  component: BlogSEO,
  parameters: {
    layout: 'fullscreen',
  },
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof meta>;

export const FullSEOMetadata: Story = {
  args: {
    post: samplePostWithSEO,
    config: seoConfig,
    options: {
      includeBreadcrumbs: true,
      includeAuthor: true,
    },
  },
  render: (args) => (
    <div className="p-8 space-y-8">
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
        <h2 className="text-2xl font-bold mb-4">📊 SEO Analysis</h2>
        {(() => {
          const analysis = analyzeContent(args.post);
          const score = getSEOScore(args.post, args.config);
          return (
            <div className="space-y-4">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-white p-4 rounded shadow">
                  <div className="text-sm text-gray-600">Word Count</div>
                  <div className="text-2xl font-bold">{analysis.wordCount}</div>
                </div>
                <div className="bg-white p-4 rounded shadow">
                  <div className="text-sm text-gray-600">Reading Time</div>
                  <div className="text-2xl font-bold">{analysis.readingTime} min</div>
                </div>
                <div className="bg-white p-4 rounded shadow">
                  <div className="text-sm text-gray-600">SEO Score</div>
                  <div className="text-2xl font-bold">{score.score}/100</div>
                </div>
                <div className="bg-white p-4 rounded shadow">
                  <div className="text-sm text-gray-600">Grade</div>
                  <div className="text-2xl font-bold uppercase">{score.grade}</div>
                </div>
              </div>
              {score.warnings.length > 0 && (
                <div className="bg-yellow-50 border border-yellow-200 rounded p-4">
                  <h3 className="font-bold mb-2">⚠️ SEO Warnings:</h3>
                  <ul className="list-disc list-inside space-y-1 text-sm">
                    {score.warnings.map((warning, i) => (
                      <li key={i}>{warning}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          );
        })()}
      </div>

      <div className="bg-green-50 border border-green-200 rounded-lg p-6">
        <h2 className="text-2xl font-bold mb-4">🏷️ Generated Metadata</h2>
        <pre className="bg-white p-4 rounded overflow-auto text-xs">
          {JSON.stringify(generateBlogMetadata(args.post, args.config), null, 2)}
        </pre>
      </div>

      <div className="bg-purple-50 border border-purple-200 rounded-lg p-6">
        <h2 className="text-2xl font-bold mb-4">📝 JSON-LD Structured Data</h2>
        <pre className="bg-white p-4 rounded overflow-auto text-xs">
          {generateBlogJSONLD(args.post, args.config, args.options)}
        </pre>
      </div>

      <div className="border-t pt-8">
        <h2 className="text-2xl font-bold mb-4">📄 Blog Preview with Reading Time</h2>
        <BlogPreview
          title={args.post.title}
          sections={args.post.sections}
          showReadingTime={true}
          date={args.post.publishedDate}
        />
      </div>

      {/* Hidden BlogSEO component (would be in <head> normally) */}
      <div style={{ display: 'none' }}>
        <BlogSEO {...args} />
      </div>
    </div>
  ),
};

export const MinimalSEOAutoGenerated: Story = {
  args: {
    post: samplePostMinimalSEO,
    config: seoConfig,
  },
  render: (args) => {
    const analysis = analyzeContent(args.post);
    const score = getSEOScore(args.post, args.config);

    return (
      <div className="p-8 space-y-8">
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6">
          <h2 className="text-2xl font-bold mb-4">🤖 Auto-Generated SEO</h2>
          <p className="mb-4">
            This post has minimal SEO metadata. The package automatically generates missing fields!
          </p>
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-white p-4 rounded shadow">
              <div className="text-sm text-gray-600">SEO Score</div>
              <div className="text-2xl font-bold">{score.score}/100</div>
              <div className="text-sm text-gray-500 mt-1">{score.grade}</div>
            </div>
            <div className="bg-white p-4 rounded shadow">
              <div className="text-sm text-gray-600">Auto-generated Excerpt</div>
              <div className="text-sm mt-2">{analysis.autoExcerpt}</div>
            </div>
          </div>
        </div>

        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
          <h2 className="text-2xl font-bold mb-4">🏷️ Auto-Generated Metadata</h2>
          <pre className="bg-white p-4 rounded overflow-auto text-xs">
            {JSON.stringify(generateBlogMetadata(args.post, args.config), null, 2)}
          </pre>
        </div>

        <BlogPreview
          title={args.post.title}
          sections={args.post.sections}
          showReadingTime={true}
        />
      </div>
    );
  },
};

export const NextJsAppRouterExample: Story = {
  args: {
    post: samplePostWithSEO,
    config: seoConfig,
  },
  render: () => (
    <div className="p-8">
      <div className="bg-slate-900 text-white rounded-lg p-6 font-mono text-sm">
        <div className="text-green-400 mb-4">// app/blog/[slug]/page.tsx</div>
        <pre className="overflow-auto">
{`import { Metadata } from 'next';
import { generateBlogMetadata, BlogSEO, BlogPreview } from 'm14i-blogging';
import { getPost } from '@/lib/blog';
import { seoConfig } from '@/config/seo';

type Props = {
  params: { slug: string }
}

// Generate metadata for SEO
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const post = await getPost(params.slug);
  return generateBlogMetadata(post, seoConfig);
}

export default async function BlogPostPage({ params }: Props) {
  const post = await getPost(params.slug);

  return (
    <>
      {/* JSON-LD structured data */}
      <BlogSEO
        post={post}
        config={seoConfig}
        options={{ includeBreadcrumbs: true }}
      />

      {/* Render blog content */}
      <BlogPreview
        title={post.title}
        sections={post.sections}
        showReadingTime={true}
      />
    </>
  );
}`}
        </pre>
      </div>
    </div>
  ),
};

export const NextJsPagesRouterExample: Story = {
  args: {
    post: samplePostWithSEO,
    config: seoConfig,
  },
  render: () => (
    <div className="p-8">
      <div className="bg-slate-900 text-white rounded-lg p-6 font-mono text-sm">
        <div className="text-green-400 mb-4">// pages/blog/[slug].tsx</div>
        <pre className="overflow-auto">
{`import Head from 'next/head';
import { BlogHead, BlogPreview } from 'm14i-blogging';
import { getPost } from '@/lib/blog';
import { seoConfig } from '@/config/seo';

export default function BlogPostPage({ post }) {
  return (
    <>
      <Head>
        <BlogHead
          post={post}
          config={seoConfig}
          options={{ includeBreadcrumbs: true }}
        />
      </Head>

      <BlogPreview
        title={post.title}
        sections={post.sections}
        showReadingTime={true}
        date={post.publishedDate}
      />
    </>
  );
}

export async function getStaticProps({ params }) {
  const post = await getPost(params.slug);
  return { props: { post } };
}`}
        </pre>
      </div>
    </div>
  ),
};
